
---
-


  hosts: webservers
  become: yes
  gather_facts: yes

  tasks:

  - name: Updating apt cache
    become: true
    apt:
      update_cache: true

  - name: installing pip3
    become: true
    apt:
      name: python3-pip
      state: latest

  - name: install flask with pip
    pip: name=flask

  - name: copy the code
    copy: 
      src: application2.py 
      dest: /application2.py

  - name: installing gunicorn
    apt:
      name: gunicorn

  - name: copy application2.py
    copy:
      src: application2.py
      dest: /home/ubuntu/application2.py
      owner: ubuntu

  - name: Run Flask app
    shell: gunicorn -w 2 -D -b 0.0.0.0:8080 application2:app


 
# haproxy configuration

- hosts: all
  gather_facts: yes
- hosts: HAproxy
  become: yes

  tasks:

  - name: updating apt cache
    become: true
    apt:
      update_cache: true

  - name: installing haproxy
    become: true
    apt:
      name: haproxy
      state: latest

  - name: deploy haproxy configuration
    template:
      src: /$PWD/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg

  - name: restarting Haproxy
    service:
      name: haproxy
      state: restarted
      
- hosts: webservers
  become: yes
  gather_facts: yes



